# Generated by Django 6.0.7 on 2026-09-10 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("course_offerings", "0003_replace_section_with_fk"),
        (
            "students",
            "0007_remove_student_address_remove_student_date_of_birth_and_more",
        ),
        (
            "teachers",
            "0008_remove_teacher_address_remove_teacher_date_of_birth_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Remark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remark_text", models.TextField()),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("PRIVATE", "Private"),
                            ("STUDENT_VISIBLE", "Student Visible"),
                        ],
                        default="PRIVATE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course_offering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="remarks",
                        to="course_offerings.courseoffering",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remarks",
                        to="students.student",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="remarks",
                        to="teachers.teacher",
                    ),
                ),
            ],
        ),
    ]
