# Generated by Django 6.0.7 on 2026-08-09 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name = 'Student',
            fields = [
                ('id', models.BigAutoField(auto_created = True, primary_key = True, serialize = False, verbose_name = 'ID')),
                ('first_name', models.CharField(max_length = 100)),
                ('last_name', models.CharField(max_length = 100)),
                ('student_email', models.EmailField(max_length = 254, unique = True)),
                ('parents_phone_number', models.CharField(max_length = 20)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices = [('M', 'Male'), ('F', 'Female')], max_length = 1)),
                ('address', models.TextField(blank = True, null = True)),
                ('student_group', models.CharField(max_length = 100)),
                ('date_of_enrollment', models.DateField(auto_now_add = True)),
                ('is_active', models.BooleanField(default = True)),
                ('created_at', models.DateTimeField(auto_now_add = True)),
                ('updated_at', models.DateTimeField(auto_now = True)),
                ('department', models.ForeignKey(blank = True, null = True, on_delete = django.db.models.deletion.PROTECT, related_name = 'students', to = 'departments.department')),
                ('teacher', models.ForeignKey(blank = True, null = True, on_delete = django.db.models.deletion.SET_NULL, related_name = 'students', to = 'teachers.teacher')),
            ],
        ),
    ]
