# Generated by Django 6.0.7 on 2026-08-20 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0001_initial'),
        ('students', '0003_link_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name = 'student',
            name = 'student_group',
        ),
        migrations.RemoveField(
            model_name = 'student',
            name = 'teacher',
        ),
        migrations.AddField(
            model_name = 'student',
            name = 'is_deleted',
            field = models.BooleanField(default = False),
        ),
        migrations.AddField(
            model_name = 'student',
            name = 'section',
            field = models.ForeignKey(blank = True, null = True, on_delete = django.db.models.deletion.PROTECT, related_name = 'students', to = 'sections.section'),
        ),
    ]
