# Generated by Django 6.0.7 on 2026-09-09 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0006_student_profile_picture_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="address",
        ),
        migrations.RemoveField(
            model_name="student",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="student",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="student",
            name="profile_picture_key",
        ),
    ]
