# Generated by Django 6.0.7 on 2026-09-15 18:26

from django.db import migrations, models


# Backfill: every Student that existed before this field was added already
# had working dashboard access under the old model (department/section were
# the only signal). Defaulting the new field to False for all of them would
# retroactively lock out every already-active student. Only a student who
# already has BOTH a Department and a Section assigned is treated as already
# "placed" - one with neither (or only one) was never really usable under
# the old model either, so it's correctly left False for an admin to finish.
def backfill_already_placed_students(apps, schema_editor):
    Student = apps.get_model("students", "Student")
    Student.objects.filter(
        department__isnull = False, section__isnull = False,
    ).update(placement_confirmed = True)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        (
            "students",
            "0007_remove_student_address_remove_student_date_of_birth_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="placement_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(backfill_already_placed_students, noop_reverse),
    ]
