# Generated by Django 6.0.7 on 2026-08-09 19:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name = 'Teacher',
            fields = [
                ('id', models.BigAutoField(auto_created = True, primary_key = True, serialize = False, verbose_name = 'ID')),
                ('first_name', models.CharField(max_length = 100)),
                ('last_name', models.CharField(max_length = 100)),
                ('employee_id', models.CharField(max_length = 20, unique = True)),
                ('email', models.EmailField(max_length = 254, unique = True)),
                ('phone_number', models.CharField(max_length = 20)),
                ('designation', models.CharField(max_length = 100)),
                ('qualification', models.CharField(max_length = 100)),
                ('gender', models.CharField(choices = [('M', 'Male'), ('F', 'Female')], max_length = 1)),
                ('date_of_birth', models.DateField()),
                ('date_of_joining', models.DateField(default = django.utils.timezone.now)),
                ('salary', models.DecimalField(decimal_places = 2, max_digits = 10)),
                ('address', models.TextField(blank = True, null = True)),
                ('is_active', models.BooleanField(default = True)),
                ('created_at', models.DateTimeField(auto_now_add = True)),
                ('updated_at', models.DateTimeField(auto_now = True)),
                ('department', models.ForeignKey(blank = True, null = True, on_delete = django.db.models.deletion.PROTECT, related_name = 'teachers', to = 'departments.department')),
            ],
        ),
    ]
