# Generated by Django 6.0.7 on 2026-08-19 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('teachers', '0003_link_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name = 'teacher',
            name = 'department',
            field = models.ForeignKey(default = 1, on_delete = django.db.models.deletion.PROTECT, related_name = 'teachers', to = 'departments.department'),
            preserve_default = False,
        ),
    ]
