# Generated by Django 6.0.7 on 2026-09-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0006_remove_teacher_email_remove_teacher_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="profile_picture_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
