# Generated by Django 6.0.7 on 2026-09-01 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="semester_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
