# Generated by Django 6.0.7 on 2026-09-14 12:24

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("remarks", "0002_grant_group_permissions"),
    ]

    operations = [
        # Ensures the PostgreSQL "vector" extension exists in whichever
        # database this migration runs against (dev, test, staging, ...),
        # rather than relying on someone having manually run
        # CREATE EXTENSION vector beforehand. Requires a DB role with
        # privilege to create extensions (the project's dev role is a
        # superuser, so this succeeds locally; a restricted-privilege
        # production role may need this run separately by a DBA).
        VectorExtension(),
        migrations.CreateModel(
            name="RemarkEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("embedding", pgvector.django.vector.VectorField(dimensions=384)),
                ("embedded_text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "remark",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedding",
                        to="remarks.remark",
                    ),
                ),
            ],
        ),
    ]
