# Generated by Django 6.0.7 on 2026-09-14 12:42

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remarkembedding",
            name="embedding",
            field=pgvector.django.vector.VectorField(dimensions=768),
        ),
    ]
