# Generated by Django 6.0.7 on 2026-09-14 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0002_grant_group_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignmentEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("suggested_score", models.PositiveIntegerField(blank=True, null=True)),
                ("strengths", models.JSONField(blank=True, default=list)),
                ("weaknesses", models.JSONField(blank=True, default=list)),
                ("ai_feedback", models.TextField(blank=True)),
                ("confidence", models.CharField(blank=True, max_length=10)),
                ("final_score", models.PositiveIntegerField(blank=True, null=True)),
                ("teacher_feedback", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AI_SUGGESTED", "AI Suggested"),
                            ("APPROVED", "Approved"),
                            ("EDITED", "Edited"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="AI_SUGGESTED",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluation",
                        to="assignments.submission",
                    ),
                ),
            ],
        ),
    ]
