# Generated by Django 6.0.7 on 2026-08-20 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0002_department_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('semester_number', models.PositiveIntegerField()),
                ('academic_year', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='departments.department')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'department', 'semester_number', 'academic_year'), name='unique_section')],
            },
        ),
    ]
